class CrateDecoder {
    contents = new Map();

    constructor() {
        this.contents.set('CAST09', 'Training Remote [Halcyon Cargo]');
        this.contents.set('BC_ST', 'Ewok Disguise [Outfit]');
        this.contents.set('AB_PQ', 'No immediate reward. -- likely part of challenge');
        this.contents.set('AB_ST', 'No immediate reward. -- likely part of challenge');
        this.contents.set('BC_TU', 'Batuu Sun Outfit [Outfit]');
        this.contents.set('FAL13', 'Stormtrooper Armor [Outfit]');
        this.contents.set('JK_ST', 'No immediate reward. -- likely part of challenge');
        this.contents.set('FG_RS', 'Gungan Personal Energy Shield [Weapon]');
        this.contents.set('AB_OP', '7-PrG Proton Grenade [Weapon]');
        this.contents.set('FG_QR', 'Condiments [Cargo]');
        this.contents.set('FAL16', 'DUM-series Pit droid, Class 2 Heads [Parts & Scraps]');
        this.contents.set('FAL09', 'Osteo Fragmenter [Parts & Scraps]');
        this.contents.set('FAL12', 'Droid Holoprojector [Parts & Scraps]');
        this.contents.set('GI_QR', 'Plush Toys [Cargo]');
        this.contents.set('FG_ST', 'Data Chip [Parts & Scraps]');
        this.contents.set('CD_ST', 'Embo-style Outfit [Outfit]');
        this.contents.set('GI_NO', 'Loth-cat Chow [Cargo]');
        this.contents.set('GI_LM', 'A99 Aquata Breather [Cargo]');
        this.contents.set('FAL15', 'Imperial E-11 Blaster Rifle [Weapon]');
        this.contents.set('FAL14', 'Computer Probe Arm (R-unit) [Parts & Scraps]');
        this.contents.set('CAST07', 'Jedi Testing Viewscreen [Halcyon Cargo]');
        this.contents.set('FAL10', 'Kyber Crystals - Green [Parts & Scraps]');
        this.contents.set('EF_TU', 'DL-44 Heavy Blaster Pistol [Weapon]');
        this.contents.set('CD_LM', 'First Order Outfit [Outfit]');
        this.contents.set('AB_LM', 'Imperial E-11 Blaster Rifle [Weapon]');
        this.contents.set('AB_QR', 'Concussion Disc [Weapon]');
        this.contents.set('BC_PQ', 'Mon Calamari Outfit [Outfit]');
        this.contents.set('FG_TU', 'Gaming Kit [Cargo]');
        this.contents.set('JK_QR', 'No immediate reward. -- likely part of challenge');
        this.contents.set('KL_QR', 'Porg Toys [Halcyon Cargo]');
        this.contents.set('DE_TU', 'DUM-series Pit droid, Class 2 Heads [Parts & Scraps]');
        this.contents.set('DE_UV', 'Magnetic Field Condenser [Parts & Scraps]');
        this.contents.set('FAL11', 'Diatium Power Core [Parts & Scraps]');
        this.contents.set('KL_OP', 'No immediate reward. -- likely part of challenge');
        this.contents.set('CAST19', 'Ship Shutdown Data [Program]');
        this.contents.set('CAST02', 'Coaxium Coordinates [Program]');
        this.contents.set('EF_LM', 'Droid Holoprojector [Parts & Scraps]');
        this.contents.set('IJ_RS', '7-PrG Proton Grenade [Weapon]');
        this.contents.set('JK_MN', 'Food Ration Packs [Cargo]');
        this.contents.set('CAST20', 'Hyperspace Tracking Schematic [Program]');
        this.contents.set('CD_TU', 'Ohnaka Transport Solutions Uniform [Outfit]');
        this.contents.set('FAL01', 'Imperial E-11 Blaster Rifle [Weapon]');
        this.contents.set('FG_LM', 'MSE-6 Series "Mouse Droid" Casing [Parts & Scraps]');
        this.contents.set('FAL30', 'Loth-cat Chow [Cargo]');
        this.contents.set('AB_UV', 'No immediate reward. -- likely part of challenge');
        this.contents.set('KL_PQ', 'No immediate reward. -- likely part of challenge');
        this.contents.set('AB_NO', 'Bowcaster [Weapon]');
        this.contents.set('FAL07', '7-PrG Proton Grenade [Weapon]');
        this.contents.set('FAL18', 'Data Chip [Parts & Scraps]');
        this.contents.set('CAST14', 'Cargo Anomalies [Program]');
        this.contents.set('DE_QR', 'Kyber Crystals - Green [Parts & Scraps]');
        this.contents.set('CAST15', 'First Order Transmitter [Halcyon Cargo]');
        this.contents.set('FAL20', 'Magnetic Field Condenser [Parts & Scraps]');
        this.contents.set('CAST11', 'Halcyon [Vehicle]');
        this.contents.set('JK_OP', 'No immediate reward. -- likely part of challenge');
        this.contents.set('KL_NO', 'No immediate reward. -- likely part of challenge');
        this.contents.set('FAL02', 'NN-14 Blaster Pistol [Weapon]');
        this.contents.set('CAST08', 'Lost Holocron [Halcyon Cargo]');
        this.contents.set('CAST06', 'Autopilot Override Program [Program]');
        this.contents.set('AB_TU', 'NN-14 Blaster Pistol [Weapon]');
        this.contents.set('FAL17', 'Security Enhanced Comlink [Parts & Scraps]');
        this.contents.set('IJ_MN', 'Tracer Beacon [Parts & Scraps]');
        this.contents.set('FAL21', 'Bowcaster [Weapon]');
        this.contents.set('FG_OP', 'Salvage Cleaning Kit [Cargo]');
        this.contents.set('BC_LM', 'Resistance Flight Uniform [Outfit]');
        this.contents.set('EF_QR', 'Diatium Power Core [Parts & Scraps]');
        this.contents.set('AB_RS', 'T-47 Airspeeder Harpoon Gun [Weapon]');
        this.contents.set('GI_MN', 'Spice [Cargo]');
        this.contents.set('FAL23', 'Neuro-Saav TE4.4 Field Quadnoculars [Cargo]');
        this.contents.set('FAL06', 'Z-6 Jetpack [Weapon]');
        this.contents.set('FG_NO', 'Food Ration Packs [Cargo]');
        this.contents.set('IJ_ST', 'No immediate reward. -- likely part of challenge');
        this.contents.set('FAL03', 'Kyber Crystals - Blue [Parts & Scraps]');
        this.contents.set('BC_MN', 'Resistance Ground Forces Outfit [Outfit]');
        this.contents.set('IJ_UV', 'Coded Communicator [Cargo]');
        this.contents.set('KL_ST', 'No immediate reward. -- likely part of challenge');
        this.contents.set('BC_OP', 'Death Star Gunner Uniform [Outfit]');
        this.contents.set('KL_LM', 'Jedi Crusader Necklace [Halcyon Cargo]');
        this.contents.set('JK_TU', 'Hayananeya Data [Program]');
        this.contents.set('CAST18', 'Ports of Call Anomalies [Ports Of Call]');
        this.contents.set('CAST17', 'All-Kit [Halcyon Cargo]');
        this.contents.set('JK_LM', 'Medical Equipment Bags [Cargo]');
        this.contents.set('KL_TU', 'No immediate reward. -- likely part of challenge');
        this.contents.set('EF_PQ', 'Osteo Fragmenter [Parts & Scraps]');
        this.contents.set('CD_QR', 'Marauder Armor [Outfit]');
        this.contents.set('JK_NO', 'Tank Containing Bacta Fluid [Cargo]');
        this.contents.set('EF_MN', 'Tracer Beacon [Parts & Scraps]');
        this.contents.set('GI_OP', 'Medical Equipment Bags [Cargo]');
        this.contents.set('BC_RS', 'Batuu Rain Outfit [Outfit]');
        this.contents.set('JK_UV', 'Tool Demagnetizer [Halcyon Cargo]');
        this.contents.set('DE_MN', 'Vaporator Blades [Parts & Scraps]');
        this.contents.set('EF_ST', 'Security Enhanced Comlink [Parts & Scraps]');
        this.contents.set('FAL24', 'Spice [Cargo]');
        this.contents.set('JK_RS', 'No immediate reward. -- likely part of challenge');
        this.contents.set('EF_UV', 'F-11D Blaster Rifle [Weapon]');
        this.contents.set('IJ_NO', 'No immediate reward. -- likely part of challenge');
        this.contents.set('FAL05', 'Resistance Flight Uniform [Outfit]');
        this.contents.set('EF_RS', 'Hang Glider [Parts & Scraps]');
        this.contents.set('FAL25', 'RA-7 Personal Servant Droid Arm [Parts & Scraps]');
        this.contents.set('CAST03', 'Droid Unbolting Program [Program]');
        this.contents.set('FAL19', 'Tracer Beacon [Parts & Scraps]');
        this.contents.set('IJ_PQ', 'Glie-44 Blaster Pistol [Weapon]');
        this.contents.set('CAST10', 'First Order Credentials [Program]');
        this.contents.set('FAL22', 'A99 Aquata Breather [Cargo]');
        this.contents.set('KL_RS', 'All-Kit [Halcyon Cargo]');
        this.contents.set('GI_PQ', 'Star Destroyer Capacitor Bearing [Parts & Scraps]');
        this.contents.set('CAST12', 'Decoy Stone [Halcyon Cargo]');
        this.contents.set('DE_PQ', 'Kyber Crystals - Blue [Parts & Scraps]');
        this.contents.set('FAL04', 'Carbon Chisel [Parts & Scraps]');
        this.contents.set('FAL29', 'Medical Equipment Bags [Cargo]');
        this.contents.set('KL_UV', 'No immediate reward. -- likely part of challenge');
        this.contents.set('IJ_TU', 'Neuro-Saav TE4.4 Field Quadnoculars [Cargo]');
        this.contents.set('EF_OP', 'Carbon Chisel [Parts & Scraps]');
        this.contents.set('DE_NO', 'AT-AT Targeting Computer [Parts & Scraps]');
        this.contents.set('CAST05', 'Datatapes [Halcyon Cargo]');
        this.contents.set('CAST01', 'Coaxium [Halcyon Cargo]');
        this.contents.set('FAL28', 'Jawa Outfit [Outfit]');
        this.contents.set('CAST16', 'Personnel Anomalies [Program]');
        this.contents.set('DE_LM', 'RA-7 Personal Servant Droid Arm [Parts & Scraps]');
        this.contents.set('FG_PQ', 'Sewing Thread [Cargo]');
        this.contents.set('CD_RS', 'Leather Armor [Outfit]');
        this.contents.set('JK_PQ', 'Engineering Tools [Halcyon Cargo]');
        this.contents.set('DE_ST', 'Kyber Crystals - Purple [Parts & Scraps]');
        this.contents.set('EF_NO', 'Computer Probe Arm (R-unit) [Parts & Scraps]');
        this.contents.set('BC_NO', 'Stormtrooper Armor [Outfit]');
        this.contents.set('IJ_QR', 'Pyro Denton Explosive [Weapon]');
        this.contents.set('FG_MN', 'First Order Binders [Parts & Scraps]');
        this.contents.set('FAL26', 'Plush Toys [Cargo]');
        this.contents.set('FG_UV', 'Neuro-Saav TE4.4 Field Quadnoculars [Cargo]');
        this.contents.set('DE_OP', 'Jawa Outfit [Outfit]');
        this.contents.set('DE_RS', 'Kyber Crystals - Red [Parts & Scraps]');
        this.contents.set('IJ_LM', 'Concussion Disc [Weapon]');
        this.contents.set('CAST13', 'Hayananeya Schematic [Program]');
        this.contents.set('FAL08', 'Concussion Disc [Weapon]');
        this.contents.set('FAL27', 'AT-AT Targeting Computer [Parts & Scraps]');
        this.contents.set('AB_MN', 'Z-6 Jetpack [Weapon]');
        this.contents.set('IJ_OP', 'Batuu Sun Outfit [Outfit]');
        this.contents.set('CAST04', 'Resistance Coordinates [Program]');
    }
}